name: Process boot.img from URL (mkbootimg)

on:
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      boot_img_url:
        description: "URL to download the boot.img file"
        required: true
        type: string
        #default: "https://dumps.tadiphone.dev/dumps/motorola/vienna/-/raw/user-14-U4UI34.8-22-7-ed299-release-keys/boot.img"  # Default URL if not provided

jobs:
  process-boot-img:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify your preferred version

      # Step 2: Ensure magiskboot is executable and process boot.img
      - name: Process boot.img
        continue-on-error: true
        run: |
          git clone https://android.googlesource.com/platform/system/tools/mkbootimg aik/master
          cd aik
          cd master
          curl -L -o boot.img "${{ github.event.inputs.boot_img_url }}"
          if [ ! -f "boot.img" ]; then
            echo "Failed to download boot.img. Exiting."
            exit 1
          fi
          python unpack_bootimg.py --boot_img boot.img
